<?xml version="1.0" encoding="utf-8"?><Database Name="books" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\books.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="booksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.book" Member="books">
    <Type Name="book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="author" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="genre" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>